### PR TITLE
Don't fail with unexpected error on unresolved assembly references

### LINKED ISSUE #1772: TrimmerRootAssembly broken in recent SDKs
Linking a project with TrimmerRootAssembly crashes the linker (using SDK 6.0.100-alpha.1.21071.6)
```xml
  <ItemGroup>
    <TrimmerRootAssembly Include="System.Runtime" />
  </ItemGroup>
```
```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/Users/sven/tmp/trimroot/trimroot.csproj]
         Fatal error in IL Linker
         Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Users/sven/tmp/trimroot/System.Runtime'.
         File name: '/Users/sven/tmp/trimroot/System.Runtime'
            at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
            at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
            at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
            at Mono.Linker.DirectoryAssemblyResolver.GetAssembly(String file, ReaderParameters parameters)
            at Mono.Linker.Steps.RootAssemblyInput.LoadAssemblyFile()
            at Mono.Linker.Steps.RootAssemblyInput.Process()
            at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
            at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
            at Mono.Linker.Pipeline.Process(LinkContext context)
            at Mono.Linker.Driver.Run(ILogger customLogger)
            at Mono.Linker.Driver.Main(String[] args)
```

This looks like it was introduced by https://github.com/mono/linker/pull/1725 @marek-safar

### PR DESCRIPTION
**Pull request by marek-safar**
Also fixes #1772

### CODE REVIEW

File: src/linker/Linker/LinkContext.cs [hunk 1]
```diff
@@ -286,22 +286,21 @@ public TypeDefinition GetType (string fullName)
...
 		}
 
 		public AssemblyDefinition Resolve (IMetadataScope scope)
 		{
 			AssemblyNameReference reference = GetReference (scope);
-			try {
-				AssemblyDefinition assembly = _resolver.Resolve (reference, _readerParameters);
-				return assembly;
-			} catch (Exception e) when (!(e is AssemblyResolutionException)) {
-				throw new AssemblyResolutionException (reference, e);
```
Comment (vitek-karas) [inline src/linker/Linker/LinkContext.cs:303]: Is the exception actually used anywhere after this change? I can't find any place which would throw it.

Comment (marek-safar) [reply src/linker/Linker/LinkContext.cs:303]: This is Cecil exception which Cecil throw but not from the code path linker uses

File: src/linker/Linker/AssemblyResolver.cs [hunk 2]
```diff
@@ -29,65 +29,55 @@
...
-
-	public class AssemblyResolver : DirectoryAssemblyResolver
+	public class AssemblyResolver : IAssemblyResolver
 	{
+		readonly Dictionary<string, AssemblyDefinition> _assemblies = new Dictionary<string, AssemblyDefinition> (StringComparer.OrdinalIgnoreCase);
+		readonly List<string> _references = new ();
+		readonly LinkContext _context;
+		readonly List<string> _directories = new ();
+		readonly Dictionary<AssemblyDefinition, string> _assemblyToPath = new ();
+		readonly List<MemoryMappedViewStream> viewStreams = new ();
```
Comment (vitek-karas) [inline src/linker/Linker/AssemblyResolver.cs:44]:
```suggestion
		readonly List<MemoryMappedViewStream> _viewStreams = new ();
```

**Review by vitek-karas — APPROVED** [review]
