### PR TITLE
Resolve custom steps from external assemblies

### LINKED ISSUE #969: Custom steps cannot be resolved from external assembly in ILLink
Currently, whenever a user tries to add a custom step to the linkers pipeline, the Driver will [try to retrieve the type](https://github.com/mono/linker/blob/b577649961239131e21288aa6b826a1e2bd92674/src/linker/Linker/Driver.cs#L646) of the custom step that was passed to the linker using the `--custom-step` flag, and fail, since there's no way for the linker to know in which assembly this type is. We should define the way in which the linker should find and resolve custom steps that are passed to it through the command line.

### PR DESCRIPTION
**Pull request by mateoatr**
Fixes #969: These changes add the ability to specify the assembly where a custom step is defined by either specifying its full path or its file name, which we'll be looked for into the additional directories passed to the linker through the command line (with `-d`).

### CODE REVIEW

File: src/linker/Linker/Driver.cs [hunk 1]
```diff
@@ -568,10 +570,16 @@ public bool Run (ILogger customLogger = null)
...
-				foreach (string custom_step in custom_steps) {
-					if (!AddCustomStep (p, custom_step))
+				
+				if (custom_steps.Any()) {
+					List<Assembly> custom_step_assemblies;
+					if (!ResolveCustomStepAssemblies (custom_steps, context.Resolver.GetSearchDirectories (), out custom_step_assemblies))
 						return false;
+
+					while (custom_steps.Any()) {
+						if (!AddCustomStep (p, custom_steps.Pop (), custom_step_assemblies))
```
Comment (vitek-karas) [inline src/linker/Linker/Driver.cs]: I think this will change the order in which the steps are added - which may change the effective order of steps - which is an unnecessary breaking change.

Comment (mateoatr) [reply src/linker/Linker/Driver.cs]: You're right, thanks for spotting this. I'll change it back.

**Comment by mateoatr** [comment]
I think that adding a new command line option here would be a better option, being more explicit in what we're doing. I'll make the changes and then add some examples in here and update the [current documentation](https://github.com/mono/linker/blob/master/src/linker/README.md) we have about adding custom steps.

File: src/linker/Linker/Driver.cs [hunk 2]
```diff
@@ -596,39 +604,25 @@ public bool Run (ILogger customLogger = null)
...
+			Assembly custom_assembly = null;
+			if (Path.IsPathRooted (arg)) {
+				var assemblyPath = Path.GetFullPath (arg);
+				if (File.Exists (assemblyPath))
+					return Assembly.LoadFrom (assemblyPath);
+				else
+					Console.WriteLine ($"Invalid assembly path '{arg}' specified for '--custom-step' option");
+			}
+			else {
+				foreach (var directory in search_directories) {
```
Comment (vitek-karas) [inline src/linker/Linker/Driver.cs]: I'm a bit nervous about this - mostly because we're combining two worlds of assemblies here. The `search_directories` are intended for resolution of assemblies for the app being linked. Now we're also using it to search for parts of the linker (the tool). This is problematic for several reasons:
* If there are potential ambiguous matches (the app and the linker using assembly with the same name) - not very likely, but still
* The linked app may not be of the same .NET Core version nor it may be the same target - for example I can link a linux app on windows. This means I'm searching through potentially linux specific directories when looking for windows assemblies.
* This also works the other way round - if I add a search directory specifically due to custom steps now I'm opening a potential issue that assemblies from that directly will be treated as part of the app.

For now I would prefer to only support the fully specified path and don't try to implement probing in any way. For the scenario we want this should not be a problem. It doesn't match the existing functionality on .NET Framework/Mono, but I don't think that's the goal we should be after.

File: src/linker/Linker/Driver.cs [hunk 3]
```diff
@@ -276,6 +278,12 @@ public bool Run (ILogger customLogger = null)
 
 							continue;
 
+						case "--custom-assembly":
```
Comment (marek-safar) [inline src/linker/Linker/Driver.cs]: Please instead of introducing option which makes sense only when used with `--custom-step` please extend `--custom-step` to take optional assembly path value

Comment (mateoatr) [reply src/linker/Linker/Driver.cs]: I've changed the way we get the custom assemblies to the other option that @vitek-karas  originally suggested (use `,,` as a separator between the custom step and the custom assembly).

Comment (marek-safar) [reply src/linker/Linker/Driver.cs]: Why `,,` ? I think a single comma should be fine. If you are concern about the name being part of type we could force some escaping in that case but don't think that will be needed at this point

File: test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj [hunk 4]
```diff
@@ -114,6 +114,7 @@
     <Content Include="LinkXml\UnusedTypeDeclarationPreservedByLinkXmlIsKept.xml" />
   </ItemGroup>
   <ItemGroup>
+    <ProjectReference Include="..\..\src\linker\Mono.Linker.csproj" />
```
Comment (marek-safar) [inline test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj]: This does not make much sense. You need to add the reference to https://github.com/mono/linker/pull/976/files#diff-38e7184cf84a72cb81b88450ae657f74R7 not here

File: src/linker/Linker/Driver.cs [hunk 5]
```diff
@@ -643,9 +668,13 @@ static IStep FindStep (Pipeline pipeline, string name)
 			return null;
 		}
 
-		static IStep ResolveStep (string type)
+		static IStep ResolveStep (string type, Assembly assembly)
 		{
 			Type step = Type.GetType (type, false);
+			if (step == null) {
```
Comment (marek-safar) [inline src/linker/Linker/Driver.cs]: The logic has to be inverted, if assembly != null it has to loop up the type in the assembly first

File: src/linker/Linker/Driver.cs [hunk 6]
```diff
@@ -588,11 +589,35 @@ public bool Run (ILogger customLogger = null)
 
 		partial void PreProcessPipeline (Pipeline pipeline);
 
+		protected static Assembly GetCustomAssembly (string arg) {
```
Comment (marek-safar) [inline src/linker/Linker/Driver.cs]: Why protected?

File: src/linker/Linker/Driver.cs [hunk 7]
```diff
@@ -588,11 +589,35 @@ public bool Run (ILogger customLogger = null)
...
+			Assembly custom_assembly = null;
```
Comment (marek-safar) [inline src/linker/Linker/Driver.cs]: This local variable is redundant

File: src/linker/Linker/Driver.cs [hunk 8]
```diff
@@ -588,11 +589,35 @@ public bool Run (ILogger customLogger = null)
...
+			if (Path.IsPathRooted (arg)) {
+				var assemblyPath = Path.GetFullPath (arg);
+				if (File.Exists (assemblyPath))
+					return Assembly.Load (File.ReadAllBytes (assemblyPath));
+				else
+					Console.WriteLine ($"The assembly '{arg}' specified for '--custom-step' option could not be found");
+			}
+			else
+				Console.WriteLine ($"The path to the assembly '{arg}' specified for '--custom-step' must be rooted");
```
Comment (marek-safar) [inline src/linker/Linker/Driver.cs]: `rooted` is not what most developers understand, please use a common word

File: src/linker/Linker/Driver.cs [hunk 9]
```diff
@@ -588,11 +589,35 @@ public bool Run (ILogger customLogger = null)
 
 		partial void PreProcessPipeline (Pipeline pipeline);
 
+		protected static Assembly GetCustomAssembly (string arg) {
+			Assembly custom_assembly = null;
+			if (Path.IsPathRooted (arg)) {
+				var assemblyPath = Path.GetFullPath (arg);
+				if (File.Exists (assemblyPath))
+					return Assembly.Load (File.ReadAllBytes (assemblyPath));
+				else
```
Comment (marek-safar) [inline src/linker/Linker/Driver.cs]: Redundant else

File: src/linker/Linker/Driver.cs [hunk 10]
```diff
@@ -588,11 +589,35 @@ public bool Run (ILogger customLogger = null)
...
+					Console.WriteLine ($"The assembly '{arg}' specified for '--custom-step' option could not be found");
+			}
```
Comment (marek-safar) [inline src/linker/Linker/Driver.cs]: Please follow existing coding style

File: src/linker/Linker/Driver.cs (hunk 3 above)
Comment (vitek-karas) [reply src/linker/Linker/Driver.cs]: Basically the only counter-example is something like `MyType,MyAssembly.dll` where on disk there's a `MyAssembly.dll.dll` - so the `.dll` is part of the assembly name and not a file extension.  If we're OK not supporting that case, I'd be perfectly fine with looking at the string after the first comma and if it has a `.dll` or `.exe` extension, then treat it as a file path. To make it even better we could say that in that case there must be just one comma - multiple commas would automatically mean to treat it as an assembly qualified type name.

Comment (marek-safar) [reply src/linker/Linker/Driver.cs]: I think we should treat anything after the comma as a file. I don't think allowing assembly-qualified name together with the full path to the file would help anyone. Using the assembly-qualified name without file path would be even stranger and in this context.

Comment (vitek-karas) [reply src/linker/Linker/Driver.cs]: I was trying to address the fact that linker today supports assembly qualified type names in this context already - so I'm trying to not break that functionality.

Comment (marek-safar) [reply src/linker/Linker/Driver.cs]: I don't think that's ever used (and we could do illink support only too)

Comment (vitek-karas) [reply src/linker/Linker/Driver.cs]: OK - I don't know how important is to keep this for mono linker - so I would vote for changing it everywhere...

File: test/Mono.Linker.Tests.Cases/CommandLine/AddCustomStep.cs [hunk 11]
```diff
@@ -1,14 +1,18 @@
...
 
 namespace Mono.Linker.Tests.Cases.CommandLine
 {
-	[SetupCompileBefore ("CustomStep.dll", new [] { "Dependencies/CustomStepDummy.cs" })]
-	[SetupLinkerArgument ("--custom-step", "CustomStep.CustomStepDummy,,CustomStep.dll")]
-	[SetupLinkerArgument ("--custom-step", "-CleanStep:CustomStep.CustomStepDummy,,CustomStep.dll")]
-	[SetupLinkerArgument ("--custom-step", "+CleanStep:CustomStep.CustomStepDummy,,CustomStep.dll")]
-	[LogContains("Custom step added")]
+
+#if NET471
```
Comment (marek-safar) [inline test/Mono.Linker.Tests.Cases/CommandLine/AddCustomStep.cs]:
```suggestion
#if !NETCOREAPP
```
